# Generated by Django 4.2 on 2023-04-06 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paymentapp', '0002_remove_currency_id_alter_currency_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('API_KEY', models.CharField(max_length=20)),
            ],
        ),
    ]
