# Generated by Django 4.2 on 2023-04-06 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paymentapp', '0003_merchant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('status', models.CharField(max_length=15)),
                ('amount', models.IntegerField()),
            ],
        ),
    ]
