# Generated by Django 4.2 on 2023-04-07 07:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paymentapp', '0004_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('amount', models.IntegerField()),
                ('currency', models.CharField(max_length=3)),
                ('description', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=15)),
                ('date', models.DateField()),
                ('number', models.IntegerField(validators=[django.core.validators.MinValueValidator(1000000000000000), django.core.validators.MaxValueValidator(9999999999999999)])),
                ('exp_month', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('exp_year', models.IntegerField(validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(9999)])),
                ('name', models.CharField(max_length=20)),
                ('cvv', models.IntegerField(validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(999)])),
                ('installments', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('type', models.IntegerField()),
            ],
        ),
    ]
