# Generated by Django 4.2 on 2023-04-10 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paymentapp', '0005_checkout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='currency',
        ),
        migrations.AddField(
            model_name='checkout',
            name='transactions',
            field=models.ManyToManyField(to='paymentapp.transaction'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='checkouts',
            field=models.ManyToManyField(to='paymentapp.checkout'),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
