# Generated by Django 4.2 on 2023-04-10 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paymentapp', '0006_remove_checkout_currency_checkout_transactions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='currency',
            field=models.ForeignKey(default='lol', on_delete=django.db.models.deletion.CASCADE, to='paymentapp.currency'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='checkout',
            name='merchant',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='paymentapp.merchant'),
            preserve_default=False,
        ),
    ]
