# Generated by Django 4.2 on 2023-04-10 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paymentapp', '0008_alter_merchant_api_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
