# Generated by Django 4.2 on 2023-04-10 21:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paymentapp', '0010_remove_checkout_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='cvv',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(999)]),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='exp_month',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='exp_year',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(9999)]),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='number',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1000000000000000), django.core.validators.MaxValueValidator(9999999999999999)]),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='transactions',
            field=models.ManyToManyField(null=True, to='paymentapp.transaction'),
        ),
    ]
