# Generated by Django 4.2 on 2023-04-12 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paymentapp', '0011_alter_checkout_cvv_alter_checkout_exp_month_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
