# Generated by Django 4.2 on 2023-04-12 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paymentapp', '0012_alter_transaction_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
