# Generated by Django 4.2 on 2023-05-06 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paymentapp', '0014_alter_checkout_date_alter_transaction_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='merchants_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
