# Generated by Django 4.2 on 2023-05-06 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paymentapp', '0015_checkout_merchants_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='merchants_name',
        ),
        migrations.AlterField(
            model_name='checkout',
            name='merchant',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
