# Generated by Django 4.2 on 2023-05-06 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paymentapp', '0016_remove_checkout_merchants_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='merchant_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='merchant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paymentapp.merchant'),
        ),
    ]
