# Generated by Django 4.2 on 2023-05-08 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paymentapp', '0017_checkout_merchant_name_alter_checkout_merchant'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='type',
            field=models.CharField(default='BNPL', max_length=4),
            preserve_default=False,
        ),
    ]
