# Generated by Django 4.2 on 2023-05-08 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paymentapp', '0018_checkout_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='type',
            field=models.CharField(default='BNPL', max_length=4),
        ),
    ]
