# Generated by Django 4.2 on 2023-05-08 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paymentapp', '0019_alter_checkout_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkout',
            old_name='merchant',
            new_name='_merchant',
        ),
        migrations.RenameField(
            model_name='checkout',
            old_name='merchant_name',
            new_name='merchan',
        ),
    ]
