# Generated by Django 4.2 on 2023-05-08 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paymentapp', '0020_rename_merchant_checkout__merchant_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkout',
            old_name='merchan',
            new_name='merchant',
        ),
    ]
