# Generated by Django 4.2 on 2023-05-09 23:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paymentapp', '0021_rename_merchan_checkout_merchant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='cvv',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(9999)]),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='exp_year',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)]),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='number',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(100000000000000), django.core.validators.MaxValueValidator(9999999999999999)]),
        ),
    ]
